src/routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\TopController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ClassNameController;
use App\Http\Controllers\Admin\ClassCategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProductClassController;
use App\Http\Controllers\Admin\ProductReviewController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\OrderPaymentController;
use App\Http\Controllers\Admin\TrackingNumberController;
use App\Http\Controllers\Admin\MailController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Admin\Auth\RegisteredUserController;
// use App\Http\Controllers\Admin\Auth\ConfirmablePasswordController;
// use App\Http\Controllers\Admin\Auth\EmailVerificationNotificationController;
// use App\Http\Controllers\Admin\Auth\EmailVerificationPromptController;
// use App\Http\Controllers\Admin\Auth\NewPasswordController;
// use App\Http\Controllers\Admin\Auth\PasswordResetLinkController;
// use App\Http\Controllers\Admin\Auth\VerifyEmailController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth:admins')->group(function () {

    // トップページ
    Route::get('/', [TopController::class, 'index'])->name('index');

    // カテゴリ
    Route::prefix('category')->name('category.')->group(function () {
        // 一覧
        Route::get('/', [CategoryController::class, 'index'])->name('index');
        // 登録
        Route::post('/store', [CategoryController::class, 'store'])->name('store');
        // CSVエクスポート
        Route::post('/export', [CategoryController::class, 'export'])->name('export');
        // CSV雛形ダウンロード
        Route::post('/template', [CategoryController::class, 'template'])->name('template');
        // CSVインポート
        Route::get('/csv', [CategoryController::class, 'csv'])->name('csv');
        Route::post('/import', [CategoryController::class, 'import'])->name('import');
    });

    // 規格名
    Route::prefix('classname')->name('classname.')->group(function () {
        // CSVエクスポート
        Route::post('/export', [ClassNameController::class, 'export'])->name('export');
        // CSV雛形ダウンロード
        Route::post('/template', [ClassNameController::class, 'template'])->name('template');
        // CSVインポート
        Route::post('/import', [ClassNameController::class, 'import'])->name('import');
    });

    // 規格カテゴリ
    Route::prefix('classcategory')->name('classcategory.')->group(function () {
        // 一覧
        Route::get('/', [ClassCategoryController::class, 'index'])->name('index');
        // 登録
        Route::post('/store', [ClassCategoryController::class, 'store'])->name('store');
        // CSVエクスポート
        Route::post('/export', [ClassCategoryController::class, 'export'])->name('export');
        // CSV雛形ダウンロード
        Route::post('/template', [ClassCategoryController::class, 'template'])->name('template');
        // CSVインポート
        Route::get('/csv', [ClassCategoryController::class, 'csv'])->name('csv');
        Route::post('/import', [ClassCategoryController::class, 'import'])->name('import');
    });

    // 商品
    Route::prefix('product')->name('product.')->group(function () {
        // 一覧
        Route::match(['get', 'post'], '/', [ProductController::class, 'index'])->name('index');
        // 作成
        Route::get('/create', [ProductController::class, 'create'])->name('create');
        // 登録
        Route::post('/store', [ProductController::class, 'store'])->name('store');
        // 編集
        Route::get('/{productId}/edit', [ProductController::class, 'edit'])->name('edit');
        // CSVエクスポート
        Route::post('/export', [ProductController::class, 'export'])->name('export');
        // CSV雛形ダウンロード
        Route::post('/template', [ProductController::class, 'template'])->name('template');
        // CSVインポート
        Route::get('/csv', [ProductController::class, 'csv'])->name('csv');
        Route::post('/import', [ProductController::class, 'import'])->name('import');
    });

    // 商品規格
    Route::prefix('{productId}/productclass')->name('productclass.')->group(function () {
        // 一覧
        Route::get('/', [ProductClassController::class, 'index'])->name('index');
        // 登録
        Route::post('/store', [ProductClassController::class, 'store'])->name('store');
    });

    // レビュー
    Route::prefix('review')->name('review.')->group(function () {
        // 一覧
        Route::match(['get', 'post'], '/', [ProductReviewController::class, 'index'])->name('index');
        // 作成
        Route::get('/create', [ProductReviewController::class, 'create'])->name('create');
        // 登録
        Route::post('/store', [ProductReviewController::class, 'store'])->name('store');
        // 編集
        Route::get('/{reviewId}/edit', [ProductReviewController::class, 'edit'])->name('edit');
        // CSVエクスポート
        Route::post('/export', [ProductReviewController::class, 'export'])->name('export');
        // CSV雛形ダウンロード
        Route::post('/template', [ProductReviewController::class, 'template'])->name('template');
        // CSVインポート
        Route::get('/csv', [ProductReviewController::class, 'csv'])->name('csv');
        Route::post('/import', [ProductReviewController::class, 'import'])->name('import');
    });

    // 受注
    Route::prefix('order')->name('order.')->group(function () {
        // 一覧
        Route::match(['get', 'post'], '/', [OrderController::class, 'index'])->name('index');
        // 作成
        Route::get('/create', [OrderController::class, 'create'])->name('create');
        // 登録
        Route::post('/store', [OrderController::class, 'store'])->name('store');
        // 編集
        Route::get('/edit/{orderId}', [OrderController::class, 'edit'])->name('edit');
        // CSVエクスポート
        Route::post('/export', [OrderController::class, 'export'])->name('export');
    });

    // 会員
    Route::prefix('user')->name('user.')->group(function () {
        // 一覧
        Route::match(['get', 'post'], '/', [UserController::class, 'index'])->name('index');
        // 作成
        Route::get('/create', [UserController::class, 'create'])->name('create');
        // 登録
        Route::post('/store', [UserController::class, 'store'])->name('store');
        // 編集
        Route::get('/edit/{userId}', [UserController::class, 'edit'])->name('edit');
        // CSVエクスポート
        Route::post('/export', [UserController::class, 'export'])->name('export');
    });

    // 入金処理
    Route::prefix('payment/{orderId}')->name('payment.')->group(function () {
        Route::get('/', [OrderPaymentController::class, 'index'])->name('index');
    });

    // 発送処理
    Route::prefix('tracking/{orderId}')->name('tracking.')->group(function () {
        Route::get('/', [TrackingNumberController::class, 'index'])->name('index');
    });

    // メール
    Route::prefix('mail/{orderId}/{templateId}')->name('mail.')->group(function () {
        Route::get('/', [MailController::class, 'index'])->name('index');
        Route::post('/confirm', [MailController::class, 'confirm'])->name('confirm');
        Route::post('/back', [MailController::class, 'back'])->name('back');
        Route::post('/send', [MailController::class, 'send'])->name('send');
    });

});

// 認証
Route::middleware('guest')->group(function () {
    Route::get('login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('login', [AuthenticatedSessionController::class, 'store']);
    Route::get('register', [RegisteredUserController::class, 'create'])->name('register');
    Route::post('register', [RegisteredUserController::class, 'store']);
});
Route::middleware('auth:admins')->group(function () {
    Route::post('logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
});

//     Route::get('forgot-password', [PasswordResetLinkController::class, 'create'])
//                 ->name('password.request');

//     Route::post('forgot-password', [PasswordResetLinkController::class, 'store'])
//                 ->name('password.email');

//     Route::get('reset-password/{token}', [NewPasswordController::class, 'create'])
//                 ->name('password.reset');

//     Route::post('reset-password', [NewPasswordController::class, 'store'])
//                 ->name('password.update');
// });

// Route::middleware('auth:admin')->group(function () {
//     Route::get('verify-email', [EmailVerificationPromptController::class, '__invoke'])
//                 ->middleware('auth:admin')
//                 ->name('verification.notice');

//     Route::get('verify-email/{id}/{hash}', [VerifyEmailController::class, '__invoke'])
//                 ->middleware(['auth:admin', 'signed', 'throttle:6,1'])
//                 ->name('verification.verify');

//     Route::post('email/verification-notification', [EmailVerificationNotificationController::class, 'store'])
//                 ->middleware(['auth:admin', 'throttle:6,1'])
//                 ->name('verification.send');

//     Route::get('confirm-password', [ConfirmablePasswordController::class, 'show'])
//                 ->middleware('auth:admin')
//                 ->name('password.confirm');

//     Route::post('confirm-password', [ConfirmablePasswordController::class, 'store'])
//                 ->middleware('auth:admin');
// });

src/routes/front.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Front\TopController;
use App\Http\Controllers\Front\ProductController;
use App\Http\Controllers\Front\ProductReviewController;
use App\Http\Controllers\Front\CartController;
use App\Http\Controllers\Front\ShoppingController;
use App\Http\Controllers\Front\MypageController;
use App\Http\Controllers\Front\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Front\Auth\RegisteredUserController;
// use App\Http\Controllers\Front\Auth\ConfirmablePasswordController;
// use App\Http\Controllers\Front\Auth\EmailVerificationNotificationController;
// use App\Http\Controllers\Front\Auth\EmailVerificationPromptController;
// use App\Http\Controllers\Front\Auth\NewPasswordController;
// use App\Http\Controllers\Front\Auth\PasswordResetLinkController;
// use App\Http\Controllers\Front\Auth\VerifyEmailController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// トップページ
Route::get('/', [TopController::class, 'index'])->name('index');

// 商品一覧
Route::get('/category{categoryId}', [ProductController::class, 'index'])->name('product.index');

// 商品検索
Route::get('/search', [ProductController::class, 'search'])->name('product.search');

// 商品詳細
Route::prefix('products')->name('product.')->group(function () {
    Route::get('/{productId}', [ProductController::class, 'show'])->name('show');
});

// 口コミ
Route::prefix('products/{productId}/comments')->name('review.')->group(function () {
    // 一覧
    Route::get('/', [ProductReviewController::class, 'index'])->name('index');
    // 詳細
    Route::get('/{reviewId}', [ProductReviewController::class, 'show'])->name('show')->where(['productId' => '[0-9]+', 'reviewId' => '\w{10,}']);
});

// 口コミ投稿
Route::prefix('products/{productId}/comments')->name('review.')->middleware('auth:users')->group(function () {
    Route::get('/create', [ProductReviewController::class, 'create'])->name('create');
    Route::post('/confirm', [ProductReviewController::class, 'confirm'])->name('confirm');
    Route::post('/back', [ProductReviewController::class, 'back'])->name('back');
    Route::post('/complete', [ProductReviewController::class, 'complete'])->name('complete');
});

// カート
Route::prefix('cart')->name('cart.')->group(function () {
    // 一覧
    Route::get('/', [CartController::class, 'index'])->name('index');
    // 登録
    Route::post('/store', [CartController::class, 'store'])->name('store');
    // 更新
    Route::put('/update', [CartController::class, 'update'])->name('update');
    // 削除
    Route::delete('/delete', [CartController::class, 'delete'])->name('delete');
});

// 購入
Route::prefix('shopping')->name('shopping.')->middleware('auth:users')->group(function () {
    // 一覧
    Route::get('/', [ShoppingController::class, 'index'])->name('index');
    // 登録
    Route::post('/', [ShoppingController::class, 'store'])->name('store');
    // 完了
    Route::get('/complete', [ShoppingController::class, 'complete'])->name('complete');
});

// 購入履歴
Route::prefix('mypage')->name('mypage.')->middleware('auth:users')->group(function () {
    // 一覧
    Route::get('/', [MypageController::class, 'index'])->name('index');
    // 詳細
    Route::get('/{orderId}', [MypageController::class, 'show'])->name('show')->where(['orderId' => '[0-9]+']);
    // 2要素認証
    Route::get('/twofactor', [MypageController::class, 'twofactor'])->name('twofactor');
    // 新規登録完了
    Route::get('/register_complete', [MypageController::class, 'registerComplete'])->name('register_complete');
});

// 認証
/*
Route::middleware('guest')->group(function () {
    Route::get('login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('login', [AuthenticatedSessionController::class, 'store']);
    Route::get('register', [RegisteredUserController::class, 'create'])->name('register');
    Route::post('register', [RegisteredUserController::class, 'store']);
});
Route::middleware('auth:users')->group(function () {
    Route::post('logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
});
*/

src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

src/app/Http/Controllers/Front/CartController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Http\Controllers\Controller;
use App\Models\Cart;
use App\Models\CartDetail;
use App\Services\CartService;
use App\Repositories\Cart\CartRepositoryInterface AS CartRepository;
use App\Repositories\CartDetail\CartDetailRepositoryInterface AS CartDetailRepository;

class CartController extends Controller
{
    private $cartService;
    private $cartRepository;
    private $cartDetailRepository;

    public function __construct
    (
        CartService $cartService,
        CartRepository $cartRepository,
        CartDetailRepository $cartDetailRepository
    )
    {
        $this->middleware('cart');
        $this->cartService = $cartService;
        $this->cartRepository = $cartRepository;
        $this->cartDetailRepository = $cartDetailRepository;
    }
    
    /**
     * カート一覧
     */
    public function index(Request $request)
    {
        $cart = $this->cartRepository->getCart(Session::get('cart_key'));
        $cart = $this->cartRepository->arrayCarts($cart);

        return view('front.cart/index', [
            'cart' => $cart
        ]);
    }

    /**
     * カート登録
     */
    public function store(Request $request)
    {
        $this->cartService->setCart(Session::get('cart_key'), $request);

        return redirect(route('cart.index'));
    }

    /**
     * カート更新
     */
    public function update(Request $request)
    {
        $this->cartService->updateCart(Session::get('cart_key'), $request);
        
        return redirect(route('cart.index'));
    }

    /**
     * カート削除
     */
    public function delete(Request $request)
    {
        $this->cartRepository->deleteCartByCart(Session::get('cart_key'), $request->input('product_class_id'));

        return redirect(route('cart.index'));
    }
}

src/app/Http/Controllers/Front/TopController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Product\ProductRepositoryInterface AS ProductRepository;

class TopController extends Controller
{
    private $productRepository;

    public function __construct
    (
        ProductRepository $productRepository
    )
    {
        $this->productRepository = $productRepository;
    }
    
    /**
     * トップページ
     */
    public function index()
    {
        // 人気の商品情報
        $params['product_ids'] = [3,2,4,1];
        $qb = $this->productRepository->searchProductFrontQuery($params);
        $popularProducts = $this->productRepository->arrayProducts($qb->get());

        return view('front.top', [
            'popularProducts' => $popularProducts
        ]);
    }
}

src/resources/views/front/review/complete.blade.php
<x-front.layout>
  
  <x-slot name="header">
    <x-front.layouts.cartheader></x-front.layouts.cartheader>
  </x-slot>
  <x-slot name="footer">
    <x-front.layouts.cartfooter></x-front.layouts.cartfooter>
  </x-slot>

  <x-front.layouts.side></x-front.layouts.side>

  <div class="col-10 p-4">
    
    <div class="col-8 mx-auto">
      <div class="card border-0 shadow-sm">
        <div class="card-header">
          レビュー投稿完了
        </div>
        <div class="card-body">
          <span class="pe-3">レビュー投稿完了いたしました</span>
          <a class="btn btn-sm btn-primary text-white" href="{{ route('product.search') }}" role="button">買い物を続ける</a>
        </div>
      </div>
    </div>

  </div>

</x-front.layout>

src/resources/views/front/review/confirm.blade.php
<x-front.layout>
  
  <x-slot name="header">
    <x-front.layouts.cartheader></x-front.layouts.cartheader>
  </x-slot>
  <x-slot name="footer">
    <x-front.layouts.cartfooter></x-front.layouts.cartfooter>
  </x-slot>

  <x-front.layouts.side></x-front.layouts.side>

  <div class="col-10 p-4">
    
    <div class="col-8 mx-auto">
      <div class="card border-0 shadow-sm">
        <div class="card-header">
          レビュー確認
        </div>
        <div class="card-body">
          <form method="POST" action="?" enctype="multipart/form-data" novalidate>
            @csrf
            <input type="hidden" name="product_id" value="{{ $productId }}">
            <input type="hidden" name="user_id" value="{{ Auth::id() }}">
            <div class="row align-items-center mb-3">
              <div class="col-3">
                <span class="pe-2">おすすめレベル</span>
              </div>
              <div class="col-9">
                <input type="hidden" name="recommend_level" value="{{ $inputs ? $inputs['recommend_level'] : '' }}">
                <div>{{ $inputs ? $inputs['recommend_level'] : '' }}</div>
              </div>
            </div>
            <div class="row align-items-center mb-3">
              <div class="col-3">
                <span class="pe-2">タイトル</span>
              </div>
              <div class="col-9">
                <input type="hidden" name="title" value="{{ $inputs ? $inputs['title'] : '' }}">
                <div>{{ $inputs ? $inputs['title'] : '' }}</div>
              </div>
            </div>
            <div class="row align-items-center mb-3">
              <div class="col-3">
                <span class="pe-2">コメント</span>
              </div>
              <div class="col-9">
                <input type="hidden" name="comment" value="{{ $inputs ? $inputs['comment'] : '' }}">
                <div>{{ $inputs ? $inputs['comment'] : '' }}</div>
              </div>
            </div>
            <div class="row align-items-center mb-4">
              <div class="col-3">
                <span class="pe-2">レビュー画像</span>
              </div>
              <div class="col-9">
                  @if ( $fileName and $reviewerUrl )
                    <img src="{{ asset('storage/images/review/temp/'.$fileName) }}">
                    <input type="hidden" name="reviewer_url" value="{{ $reviewerUrl }}">
                  @endif
              </div>
            </div>
            <div class="row align-items-center">
              <div class="col-10 text-start">
                <button type='submit' name="_method" value="post" formaction="{{ route('review.back', $productId) }}" class="btn btn-secondary btn-md">
                  修正する
                </button>
              </div>
              <div class="col-2 text-end">
                <button type='submit' name="_method" value="post" formaction="{{ route('review.complete' ,$productId) }}" class="btn btn-primary btn-md">
                  登録する
                </button>
              </div>
            </div>            
          </div>
        </form>      
      </div>
    </div>

  </div>

</x-front.layout>

src/resources/views/front/review/create.blade.php
<x-front.layout>
  
  <x-slot name="header">
    <x-front.layouts.cartheader></x-front.layouts.cartheader>
  </x-slot>
  <x-slot name="footer">
    <x-front.layouts.cartfooter></x-front.layouts.cartfooter>
  </x-slot>

  <x-front.layouts.side></x-front.layouts.side>

  <div class="col-10 p-4">
    
    <div class="col-8 mx-auto">
      <div class="card border-0 shadow-sm">
        <div class="card-header">
          レビュー投稿
        </div>
        <div class="card-body">
          <form method="POST" action="?" enctype="multipart/form-data" novalidate>
            @csrf
            <input type="hidden" name="product_id" value="{{ $productId }}">
            <input type="hidden" name="user_id" value="{{ Auth::id() }}">
            <div class="row align-items-center mb-3">
              <x-front.form.review.recommend-level
                recommend_level="recommend_level"
                :select="config('star')"
                :value_recommend_level="old('recommend_level') ? old('recommend_level') : ''"/>
            </div>
            <div class="row align-items-center mb-3">
              <x-front.form.review.title
                title="title"
                :value_title="old('title') ? old('title') : ''"/>
            </div>
            <div class="row align-items-center mb-3">
              <x-front.form.review.comment
                comment="comment"
                :value_comment="old('comment') ? old('comment') : ''"
                :rows="10"/>
            </div>
            <div class="row align-items-center mb-4">
              <div class="col-3">
                <span class="pe-2">レビュー画像</span>
              </div>
              <div class="col-9">
                <input type="file" name="image" accept="image/png,image/jpeg,image/jpg,image/gif" />
              </div>
            </div>
            <div class="row align-items-center">
              <div class="col-10 text-start">
                <button type="button" onclick="history.back()" class="btn btn-secondary btn-md">
                  戻る
                </button>
              </div>
              <div class="col-2 text-end">
                <button type="submit" name="_method" value="post" formaction="{{ route('review.confirm', $productId) }}" class="btn btn-primary btn-md">
                  確認する
                </button>
              </div>
            </div>            
          </div>
        </form>      
      </div>
    </div>

  </div>

</x-front.layout>

src/resources/views/front/review/index.blade.php
<x-front.layout>
  
  <x-slot name="header">
    <x-front.layouts.header></x-front.layouts.header>
  </x-slot>
  <x-slot name="footer">
    <x-front.layouts.footer></x-front.layouts.footer>
  </x-slot>
  <x-slot name="left"></x-slot>
  <x-slot name="right"></x-slot>
  
  <div id="content">
    フロント
  </div>

</x-front.layout>